In [10]:
csv_file = r'/Users/pankaj/dev/data/sample/movies_ratings.csv'

import  tensorflow as tf
dataset = tf.data.Dataset.from_tensor_slices(list(range(10)))

In [23]:
tf.data.experimental.make_csv_dataset(csv_file, batch_size =2)

<PrefetchDataset shapes: OrderedDict([(\ufeffuserName, (2,)), (userId, (2,)), (movieName, (2,)), (movieId, (2,)), (rating, (2,))]), types: OrderedDict([(\ufeffuserName, tf.string), (userId, tf.int32), (movieName, tf.string), (movieId, tf.int32), (rating, tf.int32)])>

In [4]:
 ds = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])

In [13]:
ds1 = ds.map(lambda x :2*x)

In [14]:
ds2= ds1.batch(2)

In [20]:
ds3= ds2.batch(1)

In [21]:
for d in ds3:
    print(d.numpy())

[[16  6]]
[[ 0 16]]
[[4 2]]


In [30]:
import pandas as pd
df = pd.read_csv(csv_file)
ds = tf.data.Dataset.from_tensor_slices(dict(df))

In [40]:
for key  in ds:
    for k , v in key.items():
        print(v.numpy())

b'Alice'
1
b'The Shawshank Redemption\xc2\xa0\xc2\xa0'
1
4
b'Alice'
1
b'The Godfather'
2
3
b'Alice'
1
b'The Godfather: Part II'
3
1
b'Alice'
1
b'The Dark Knight\xc2\xa0'
4
5
b'Alice'
1
b'12 Angry Men'
5
3
b'Alice'
1
b"Schindler's List"
6
3
b'Alice'
1
b'The Lord of the Rings: The Return of the King'
7
2
b'Alice'
1
b'Pulp Fiction'
8
2
b'Alice'
1
b'The Good, the Bad and the Ugly\xc2\xa0'
9
3
b'Alice'
1
b'Fight Club'
10
1
b'Bob '
2
b'The Godfather: Part II'
3
5
b'Bob '
2
b'The Dark Knight\xc2\xa0'
4
4
b'Bob '
2
b'12 Angry Men'
5
4
b'Bob '
2
b'Fight Club'
10
4
b'Bob '
2
b'The Good, the Bad and the Ugly\xc2\xa0'
9
2
b'Carl '
3
b'The Shawshank Redemption\xc2\xa0\xc2\xa0'
1
1
b'Carl '
3
b'The Godfather'
2
1
b'Carl '
3
b'The Godfather: Part II'
3
5
b'Carl '
3
b'Pulp Fiction'
8
2
b'Carl '
3
b'The Good, the Bad and the Ugly\xc2\xa0'
9
3
b'Deb'
4
b'The Godfather'
2
5
b'Deb'
4
b'The Godfather: Part II'
3
1
b'Deb'
4
b'The Dark Knight\xc2\xa0'
4
1
b'Deb'
4
b'12 Angry Men'
5
4
b'Earl'
5
b"Schindler's 