In [1]:
from gensim.test.utils import common_texts, get_tmpfile

In [3]:
from gensim.models import Word2Vec

In [4]:
model = Word2Vec(common_texts, size=100, window=5, min_count=1, workers=4)

In [5]:
model

In [6]:
 model.wv['computer'] 

array([ 0.00478557, -0.00394222, -0.00402469,  0.00052143, -0.00017446,
        0.00296587,  0.00367646, -0.00175098,  0.00122099,  0.00462338,
        0.00130425,  0.00012867, -0.00321779, -0.00343432,  0.00296984,
       -0.00415607,  0.00466341,  0.00022777, -0.0034161 ,  0.0049446 ,
        0.00446826, -0.00129668,  0.00090647,  0.00257874, -0.00252605,
       -0.00431725,  0.00339594, -0.00098609,  0.00476491,  0.00115034,
       -0.00076247, -0.00333627, -0.00317678, -0.00211756,  0.00142131,
        0.00129768, -0.00334435, -0.00264842,  0.00044777,  0.00097956,
        0.00448289, -0.0007032 , -0.00312139, -0.0047846 ,  0.00070562,
       -0.00113472,  0.00244009, -0.0039771 ,  0.00488114, -0.00131668,
       -0.00086591, -0.00395425, -0.00383114, -0.00350589, -0.00141142,
       -0.00430253, -0.00046495,  0.00103476,  0.00263787, -0.0017483 ,
       -0.00350923, -0.00114518,  0.00164449,  0.00423219, -0.00351921,
       -0.00374284, -0.00325227,  0.00141217,  0.00276231, -0.00

In [8]:
model.wv['computer']

array([ 0.00478557, -0.00394222, -0.00402469,  0.00052143, -0.00017446,
        0.00296587,  0.00367646, -0.00175098,  0.00122099,  0.00462338,
        0.00130425,  0.00012867, -0.00321779, -0.00343432,  0.00296984,
       -0.00415607,  0.00466341,  0.00022777, -0.0034161 ,  0.0049446 ,
        0.00446826, -0.00129668,  0.00090647,  0.00257874, -0.00252605,
       -0.00431725,  0.00339594, -0.00098609,  0.00476491,  0.00115034,
       -0.00076247, -0.00333627, -0.00317678, -0.00211756,  0.00142131,
        0.00129768, -0.00334435, -0.00264842,  0.00044777,  0.00097956,
        0.00448289, -0.0007032 , -0.00312139, -0.0047846 ,  0.00070562,
       -0.00113472,  0.00244009, -0.0039771 ,  0.00488114, -0.00131668,
       -0.00086591, -0.00395425, -0.00383114, -0.00350589, -0.00141142,
       -0.00430253, -0.00046495,  0.00103476,  0.00263787, -0.0017483 ,
       -0.00350923, -0.00114518,  0.00164449,  0.00423219, -0.00351921,
       -0.00374284, -0.00325227,  0.00141217,  0.00276231, -0.00

In [ ]:
from scipy.spatial import distance
distance.cosine(doc[3].vector, doc[4].vector)

In [19]:
model.wv['human']

array([-2.3029768e-03,  4.7192788e-03,  3.3890981e-05, -2.1775898e-04,
        3.7646901e-03,  1.4372001e-03,  1.7625868e-04,  3.6371252e-03,
       -2.7506417e-03, -4.8967395e-03, -4.1120253e-03, -4.9756910e-03,
        4.0469468e-03, -2.4848601e-03,  4.4954740e-03, -3.9058507e-03,
       -2.3789834e-03,  3.7424406e-04,  4.5298729e-03,  3.3177494e-03,
       -1.4299009e-04, -4.4938005e-03,  3.1158177e-03, -3.4184600e-04,
       -2.6196158e-03, -4.1339262e-03,  3.0003095e-03, -4.6971072e-03,
       -3.5061864e-03,  4.7880430e-03,  1.6296825e-03,  2.2237138e-03,
       -2.4792214e-03,  2.8076747e-03,  3.2431441e-03,  3.8472130e-03,
       -3.4380800e-03, -3.5404332e-03,  2.5934395e-03,  3.2883317e-03,
        1.4316790e-03,  3.6272926e-03,  2.7161790e-03,  2.4263947e-03,
        9.3511381e-04,  1.9898564e-03,  1.9675614e-03, -1.2903531e-04,
        2.5506122e-03,  6.6696734e-06, -4.7440995e-03, -2.6184572e-03,
        1.8904785e-03, -7.6077157e-04, -4.5675877e-03, -2.9509920e-03,
      

In [5]:
model.wv.similarity('human', 'computer')

0.019517414

In [23]:
from scipy.spatial import distance
1-distance.cosine(model.wv['human'], model.wv['computer'])

0.014052648097276688

In [28]:
ch_dot =model.wv['human'].dot(model.wv['computer'])

In [33]:
import numpy as np
h_mag =np.linalg.norm(model.wv['human'])
c_mag =np.linalg.norm(model.wv['computer'])

In [34]:
ch_dot/(h_mag*c_mag)

0.014052651

In [35]:
from gensim.models import word2vec

sentences = word2vec.Text8Corpus('../data/text8')
model = word2vec.Word2Vec(sentences, size = 200, hs =1 )
model.wv.similarity('man', 'woman')

0.6548475